name: update-readme

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
      - name: Run the script
        run: python scripts/readme_update.py
      - name: Commit files
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add README.md
          git commit -m "Updated readme with the markdown files"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}